# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Morgan Fell
tagline:          'Personal Site'
description:      'Morgan is a Senior IT Administrator from Cumbria, England, specialising in cloud and virtualisation technologies.'
url:              https://morganfell.dev/
baseurl:          /


paginate:         5

# Custom vars
version:          0.02

github:
  repo:           https://github.com/MorganFellDEV

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: Morgan Fell
  twitter: _morganfell
twitter:
  username: _morganfell
  card: summary_large_image
social:
  name: Morgan Fell
  links:
    - https://twitter.com/_morganfell
    - https://www.linkedin.com/in/MorganFell1
    - https://github.com/MorganFellDEV

timezone: Europe/London