# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Morgan Fell
tagline:          'Personal Site'
description:      'Senior IT Admin from Cumbria, England. Microsoft Certified Azure Administrator'
url:              https://morganfell.dev/
baseurl:          /

author:
  name:           'Morgan Fell'
  url:            https://morganfell.dev

paginate:         5

# Custom vars
version:          0.02

github:
  repo:           https://github.com/MorganFellDEV
